//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorMessage
    {
        public int Id { get; set; }
        public int MsgId { get; set; }
        public string MessageEN { get; set; }
        public string MessagePL { get; set; }
        public string BackController { get; set; }
        public string BackAction { get; set; }
    }
}
