//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SysCode { get; set; }
        public int IntValue { get; set; }
        public string StrValue { get; set; }
        public bool IsActive { get; set; }
    }
}
