//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsInService
    {
        public int Id { get; set; }
        public int DeskId { get; set; }
        public int AgentId { get; set; }
        public int TicketId { get; set; }
        public System.DateTime TicketTime { get; set; }
        public int TicketNumber { get; set; }
        public System.DateTime FirstCallTime { get; set; }
        public System.DateTime LastCallDate { get; set; }
        public int CallCount { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsServed { get; set; }
        public System.DateTime ServiceEndTime { get; set; }
        public int DepartmentId { get; set; }
        public int ServiceTypeId { get; set; }
        public string DepartmentName { get; set; }
        public string ServiceTypeName { get; set; }
        public string DeskName { get; set; }
        public string Status { get; set; }
        public int ForwardedBy { get; set; }
        public int ForwardedTo { get; set; }
        public string DeptCode { get; set; }
        public bool PlaySound { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Desk Desk { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
