//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketsInServices = new HashSet<TicketsInService>();
        }
    
        public int Id { get; set; }
        public int ServiceTypeId { get; set; }
        public System.DateTime TicketTime { get; set; }
        public int CustomerId { get; set; }
        public int TicketNumber { get; set; }
        public int TicketPin { get; set; }
        public bool IsCalled { get; set; }
        public int Priority { get; set; }
        public int ForwardedBy { get; set; }
        public System.DateTime CallTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketsInService> TicketsInServices { get; set; }
    }
}
