//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTIP2
    {
        public Nullable<long> Id { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int DeskId { get; set; }
        public string DeskName { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<System.DateTime> TicketDay { get; set; }
        public Nullable<int> MaxTN { get; set; }
        public string DeptCode { get; set; }
    }
}
