//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTNrNotCalled
    {
        public long Id { get; set; }
        public Nullable<int> MaxTN { get; set; }
        public int ServiceTypeId { get; set; }
        public Nullable<System.DateTime> TicketDay { get; set; }
        public int IsCalled { get; set; }
    }
}
